# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df91b34994d801adc6bb56531ffa59d887c5947ce2f24de971e1b8922931c8c2bd04a077e89d8d28718f92e7d91c15c7b7fc4217378ce6c7b2c37a39e1192f1

test:
  secret_key_base: ed1f9c0ec08c9337970f1391717eeab385a8a8ddc3beae3d3b305456e49d4417b7874631e837806e9b414f07596c8060db5f74b5625beac18568f4fe96ff8d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
